from common import page

BODY = """
<div class="hero">
  <h1>Learn <em>LaTeX</em>, <em>Manim</em> &amp; <em>manim-slides</em><br>completely offline</h1>
  <p class="sub">A free course that takes you from zero to animated math presentations —
  with live playgrounds, real rendered animations and click-through slide decks.
  No internet, no account, no installs needed to read it.</p>
  <div class="pillrow">
    <a class="pill" href="https://github.com/Alamin-H-M/manim-slides-academy/releases/latest/download/manim-slides-academy-offline.zip" style="border-color:var(--accent);color:var(--accent)">⬇ Download the whole course (1.6 MB ZIP) — use it forever offline</a>
  </div>
  <div class="pillrow">
    <span class="pill">⚡ loads instantly</span>
    <span class="pill">📴 100% offline</span>
    <span class="pill">🧠 minimal brain-drain: one idea at a time</span>
    <span class="pill">🔓 open source · AI-generated</span>
  </div>
</div>

<div class="cards">
  <div class="card">
    <h3>🛠 Setup (once, ~20 min)</h3>
    <p>Python, Manim, manim-slides, LaTeX and VS Code — the most efficient fully-offline
    toolchain, with an installer-checklist you can tick off.</p>
    <a class="go" href="setup.html">Set up my machine →</a>
  </div>
  <div class="card">
    <h3>1 · LaTeX</h3>
    <p>The language of mathematical writing. 6 topics, every example is a <b>live playground</b> —
    edit the code, watch the math re-render instantly.</p>
    <a class="go" href="latex.html">Start LaTeX →</a>
  </div>
  <div class="card">
    <h3>2 · Manim</h3>
    <p>Programmatic animation. 6 topics, 24 <b>real rendered animations</b> next to the exact
    code that produced them.</p>
    <a class="go" href="manim.html">Start Manim →</a>
  </div>
  <div class="card">
    <h3>🔁 Practice</h3>
    <p>36 spaced-repetition flashcards across all three domains. 5 minutes a day —
    the single most evidence-backed way to make it stick.</p>
    <a class="go" href="practice.html">Review today's cards →</a>
  </div>
  <div class="card">
    <h3>🏆 Capstone</h3>
    <p>Build a complete animated Pythagorean-theorem talk in 5 milestones with fading
    hints — then export it to offline HTML and PowerPoint.</p>
    <a class="go" href="capstone.html">Start building →</a>
  </div>
  <div class="card">
    <h3>📖 Reference</h3>
    <p>Every command from all three tools on one filterable, printable page. Your
    companion after the course.</p>
    <a class="go" href="reference.html">Look something up →</a>
  </div>
  <div class="card">
    <h3>3 · manim-slides</h3>
    <p>Turn animations into presentations. 3 topics with <b>click-through interactive decks</b>
    embedded in the page.</p>
    <a class="go" href="slides.html">Start manim-slides →</a>
  </div>
</div>

<h2>How this course keeps your brain fresh</h2>
<p class="lead">Learning three tools at once is usually overwhelming. This course is engineered against that:</p>
<table>
  <tr><th>Principle</th><th>How it's applied here</th></tr>
  <tr><td><b>One idea per topic</b></td><td>Each topic teaches exactly one concept. No topic depends on anything you haven't seen yet.</td></tr>
  <tr><td><b>2 easy → 2 harder</b></td><td>Every topic has two gentle examples, then two that stretch the same idea further. You always know which is which — look for the <span style="color:#4ade80">EASY</span> / <span style="color:#fbbf24">LEVEL UP</span> badge.</td></tr>
  <tr><td><b>Do, don't just read</b></td><td>LaTeX examples are editable live. Manim examples show the real video. Slide examples are decks you click through yourself.</td></tr>
  <tr><td><b>Test yourself</b></td><td>Every chapter ends with self-check exercises: quizzes that respond instantly, and open problems with hidden solutions.</td></tr>
  <tr><td><b>Track progress</b></td><td>Tick "mark done" on each topic — it's remembered next time you open the site (stored only in your browser).</td></tr>
</table>

<h2>The path — a complete learning system</h2>
<p class="lead">This is not just reading material. It's a full loop based on how memory actually works:
<b>guess first</b> (pretests) → <b>learn by doing</b> (chapters) → <b>build for real</b> (capstone) →
<b>keep it forever</b> (spaced practice) → <b>look things up</b> (reference).</p>
<pre><code>  Setup ──▶ LaTeX ──▶ Manim ──▶ manim-slides ──▶ 🏆 Capstone project
 ~20 min    ~2 h      ~3 h        ~1.5 h            one afternoon
                                                        │
              🔁 Practice (5 min/day, spaced cards) ◀───┘──▶ 📖 Reference (forever)</code></pre>

<div class="note"><b>Honesty note</b>
This entire course was generated by an AI and packaged as open source (MIT). Every code
example was actually executed and every animation on these pages is the real render of the
code beside it — but treat it like any community resource: if something looks wrong,
<a href="https://github.com/Alamin-H-M/manim-slides-academy">open an issue or a pull request</a>. Contributions welcome!</div>
"""

def render():
    return page("index.html", "Home", BODY, desc='Learn LaTeX, Manim and manim-slides completely free and offline: live LaTeX playgrounds, 24 rendered Manim animation examples with source code, interactive slide decks, quizzes and exercises. Open-source beginner course.')